
export const sheetHeaderEntries = [
    "character name",
    "alignment",
    "race",
    "background",
    "class",
    "subclass",
    "level",
] as const;
export const attributes = [
    "HD",
    "HP",
    "THP",
    "AC",
    "movement",
    "initiative",
    "passive perception",
    "proficiency bonus",
] as const;
export const allAlignments = [
    "",
    "lawful good",
    "neutral good",
    "chaotic good",
    "lawful neutral",
    "true neutral",
    "chaotic neutral",
    "lawful evil",
    "neutral evil",
    "chaotic evil",
] as const;
export const allcharacterClasses = [
    "",
    "artificer",
    "barbarian",
    "bard",
    "cleric",
    "druid",
    "fighter",
    "monk",
    "paladin",
    "ranger",
    "rogue",
    "sorcerer",
    "warlock",
    "wizard",
] as const;
export const allCharacterSubClasses = {
    artificer: [
        "",
        "alchemist",
        "armorer",
        "artillerist",
        "battle smith",
    ],
    barbarian: [
        "",
        "path of the ancestral guardian",
        "path of the battlerager",
        "path of the beast",
        "path of the berserker",
        "path of the storm herald",
        "path of the totem warrior",
        "path of the wild magic",
        "path of the zealot",
    ],
    bard: [
        "",
        "college of creation",
        "college of eloquence",
        "college of glamour",
        "college of lore",
        "college of spirits",
        "college of swords",
        "college of valor",
        "college of whispers",
    ],
    cleric: [""],
    druid: [""],
    fighter: [""],
    monk: [""],
    paladin: [""],
    ranger: [""],
    rogue: [""],
    sorcerer: [""],
    warlock: [""],
    wizard: [""],
} as const;
export const allBackgrounds = [
    "",
    "acolyte",
] as const;
export const allRaces = [
    "",
    "human",
] as const;
export const allAbilities = [
    "strength",
    "dexterity",
    "constitution",
    "intelligence",
    "wisdom",
    "charisma",
] as const;
export const allSkills = [
    "acrobatics",
    "animal_handling",
    "arcana",
    "athletics",
    "deception",
    "history",
    "insight",
    "intimidation",
    "investigation",
    "medicine",
    "nature",
    "perception",
    "performance",
    "persuasion",
    "religion",
    "sleight_of_hand",
    "stealth",
    "survival",
] as const;
export const skillsByAbility = {
    athletics: "strength",
    acrobatics: "dexterity",
    sleight_of_hand: "dexterity",
    stealth: "dexterity",
    arcana: "intelligence",
    history: "intelligence",
    investigation: "intelligence",
    nature: "intelligence",
    religion: "intelligence",
    animal_handling: "wisdom",
    insight: "wisdom",
    medicine: "wisdom",
    perception: "wisdom",
    survival: "wisdom",
    deception: "charisma",
    intimidation: "charisma",
    performance: "charisma",
    persuasion: "charisma",
} as const;
